config/routes.rb
Rails.application.routes.draw do
  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  validates_presence_of :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    @student.save

    redirect_to student_path(@student)
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    @student.save

    redirect_to student_path(@student)
  end

  def destroy
    student = Student.find(params[:id])
    student.destroy

    redirect_to students_path
  end

private
  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Students</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit 'Submit' %>
<% end %>

app/views/students/edit.html.erb
<a class= 'button' href=<%= new_student_path %>>Create New Student</a>
<br>
<a class= 'button' href=<%= students_path %>>All Students</a>
<br>

<h2>Edit <%= @student.name %> here!</h2>

<%= render partial: "form" %>

app/views/students/index.html.erb
<h3>All Students</h3>

<a class= 'button' href=<%= new_student_path %>>Create New Student</a>
<br>
<a class= 'button' href=<%= students_path %>>All Students</a>
<br>

<ul>
  <% @students.each do |student| %>
  <li class=student_<%= student.id %>>
    <%= link_to student.name, student_path(student) %>
    <%= link_to "Delete", student_path(student), method: "delete" %>
  </li>
  <% end %>
</ul>

app/views/students/new.html.erb
<a class= 'button' href=<%= new_student_path %>>Create New Student</a>
<br>
<a class= 'button' href=<%= students_path %>>All Students</a>
<br>

<h2>Create a new student here!</h2>

<%= render partial: 'form' %>

app/views/students/show.html.erb
<a class= 'button' href=<%= new_student_path %>>Create New Student</a>
<br>
<a class= 'button' href=<%= students_path %>>All Students</a>
<br>

<h3>Student name:<%= @student.name %></h3>